{
 "title": "RaspiWeather",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_temperature{job=\"raspiweather\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensor_temperature{job=\"raspiweather\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_humidity{job=\"raspiweather\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sensor_humidity{job=\"raspiweather\"}",
     "legendFormat": "Humidity"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_pressure{job=\"raspiweather\"} * 0.75",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure Timeline",
   "type": "timeseries",
   "description": "mm Hg",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "sensor_pressure{job=\"raspiweather\"} * 0.75",
     "legendFormat": "Pressure"
    },
    { "expr": "vector(760)", "legendFormat": "Normal Pressure" }
   ]
  }
 ]
}